name: mri
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - contourpy=1.2.0
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - expat=2.5.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=73.1
  - intel-openmp=2023.1.0
  - joblib=1.2.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libllvm14=14.0.6
  - libpng=1.6.39
  - libpq=12.17
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - lz4-c=1.9.4
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - munkres=1.1.4
  - mysql=5.7.24
  - ncurses=6.4
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.4.0
  - openssl=3.0.13
  - packaging=23.2
  - pandas=2.2.1
  - patsy=0.5.3
  - pcre2=10.42
  - pillow=10.2.0
  - pip=23.3.1
  - ply=3.11
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - python=3.12.2
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - pytz=2023.3.post1
  - qt-main=5.15.2
  - readline=8.2
  - scikit-learn=1.3.0
  - scipy=1.12.0
  - setuptools=68.2.2
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.41.2
  - statsmodels=0.14.0
  - tbb=2021.8.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - tornado=6.3.3
  - pytorch=2.4
  - torchvision
  - torchaudio
  - tensorboard
  - tzdata=2024a
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - biopython==1.83
      - pycirclize==1.4.0
      - seaborn==0.13.2
      - tqdm==4.66.4
      - torchviz=0.1.1